# -*- mode: ruby -*-
# vi: set ft=ruby :
BOXNAME = "bento/centos-7"

Vagrant.configure("2") do |config|
  config.vm.box = "base"
  config.hostmanager.enabled = true
  config.hostmanager.include_offline = true

  config.vm.define "dbserver" do |dbserver|
    dbserver.vm.box = BOXNAME
    dbserver.vm.network :private_network, ip: "10.0.0.10"
    dbserver.vm.hostname = "dbserver"
    dbserver.vm.provision "shell", path: "provision/dbserver.sh"

    dbserver.vm.provider "virtualbox" do |v|
      v.name = "front"
    end
  end

  config.vm.define "front" do |front|
    front.vm.box = BOXNAME
    front.vm.network :private_network, ip: "10.0.0.11"
    front.vm.network "forwarded_port", guest: 8080, host: 8080
    front.vm.hostname = "front"
    front.vm.provision "shell", path: "provision/front.sh"

    front.vm.provider "virtualbox" do |v|
      v.memory = 512
      v.name = "front"
    end
  end

end
